# SPDX-License-Identifier: MIT
---
- name: Update aide check cron configuration if necessary
  ansible.builtin.lineinfile:
    path: /etc/crontab
    regexp: "^.* root {{ __aide_bin_path }} --check"
    line: "{{ aide_cron_interval }} root {{ __aide_bin_path }} --check"
  when:
    - aide_cron_check is not none
    - aide_cron_check | bool

- name: Remove aide check cron configuration if necessary
  ansible.builtin.lineinfile:
    path: /etc/crontab
    state: absent
    regexp: "^.* root {{ __aide_bin_path }} --check"
  when:
    - aide_cron_check is not none
    - not aide_cron_check | bool
